const ctrl = require('./controller');
const enforcement = require('./enforcement');
const csp = require('./csp');
const egress = require('./egress');
const instructionPatterns = require('./instructionPatterns');
const knowledge = require('./knowledge');
const auditRedaction = require('./auditRedaction');
const { requireInstanceAdmin } = require('./guard');
const agentMetrics = require('../Agents/metricsController');

exports.init = (app) => {
    app.get('/api/v2/instance/public-config', ctrl.publicConfig);

    const admin = '/api/v2/instance';
    app.use(admin, (req, res, next) => (req.path === '/public-config' ? next() : requireInstanceAdmin(req, res, next)));
    app.get(`${admin}/access`, ctrl.access);
    app.get(`${admin}/settings`, ctrl.getSettings);
    app.put(`${admin}/settings`, ctrl.putSettings);
    app.post(`${admin}/settings/test`, ctrl.testSettings);
    app.get(`${admin}/health`, ctrl.health);
    app.get(`${admin}/metrics`, agentMetrics.instanceMetrics);
    app.post(`${admin}/maintenance`, ctrl.setMaintenance);
    app.get(`${admin}/upgrade`, ctrl.upgrade);
    app.post(`${admin}/migrations/run`, ctrl.runMigrations);
    app.get(`${admin}/logs`, ctrl.tailLog);
    app.get(`${admin}/logs/files`, ctrl.listLogs);
    app.get(`${admin}/logs/download`, ctrl.downloadLog);
    app.get(`${admin}/backups`, ctrl.listBackups);
    app.post(`${admin}/backups`, ctrl.createBackup);
    app.get(`${admin}/backups/:name/manifest`, ctrl.backupManifest);
    app.get(`${admin}/backups/:name/download`, ctrl.downloadBackup);
    app.post(`${admin}/backups/:name/restore`, ctrl.restoreBackup);
    app.delete(`${admin}/backups/:name`, ctrl.deleteBackup);
    app.get(`${admin}/ai/providers`, ctrl.aiProviders);
    app.get(`${admin}/stats`, ctrl.stats);
    app.get(`${admin}/companies`, ctrl.companies);
    app.get(`${admin}/audit-export`, ctrl.auditExport);
    app.post(`${admin}/audit/:companyId/redact-person`, auditRedaction.redactPerson);
    app.get(`${admin}/csp`, csp.summary);
    app.get(`${admin}/enforcement`, enforcement.summary);
    app.put(`${admin}/enforcement/default`, enforcement.setDefault);
    app.get(`${admin}/enforcement/:companyId/decisions`, enforcement.decisions);
    app.put(`${admin}/enforcement/:companyId/mode`, enforcement.setMode);
    app.get(`${admin}/egress`, egress.summary);
    app.put(`${admin}/egress/:companyId`, egress.setHosts);
    app.get(`${admin}/instruction-patterns`, instructionPatterns.summary);
    app.post(`${admin}/instruction-patterns`, instructionPatterns.add);
    app.delete(`${admin}/instruction-patterns/:id`, instructionPatterns.remove);
    app.get(`${admin}/knowledge`, knowledge.summary);
    app.get(`${admin}/knowledge/:companyId`, knowledge.workspace);
    app.post(`${admin}/knowledge/:companyId/reindex`, knowledge.reindex);
    app.post(`${admin}/knowledge/:companyId/reindex/cancel`, knowledge.cancelReindex);
    app.post(`${admin}/knowledge/:companyId/reembed`, knowledge.reembed);
    app.post(`${admin}/knowledge/:companyId/retry-files`, knowledge.retryFiles);
    app.post(`${admin}/knowledge/:companyId/erase/document`, knowledge.eraseDocument);
    app.post(`${admin}/knowledge/:companyId/erase/person`, knowledge.erasePerson);
    app.get(`${admin}/knowledge/:companyId/exclusions`, knowledge.exclusions);
    app.post(`${admin}/knowledge/:companyId/exclusions/:exclusionId/remove`, knowledge.removeExclusion);
};
