/* What the audit log's rows are called in English. The export's label column reads these, and
 * tests/conventions/audit-event-labels.test.js holds the web app's words (AuditEvents and AuditActions in
 * frontend/src/locales/en.js) to them, so a key added here or written anywhere on the server has words on screen. */

/* `action` of a row: what happened. */
const EVENTS = Object.freeze({
    'agent.action': 'An agent made a change',
    'agent.action_refused': 'An agent\'s change was blocked',
    'agent.action_undone': 'An agent\'s change was undone',
    'agent.proposal_decided': 'Decided an agent\'s proposal',
    'agent.deleted': 'Deleted an agent',
    'agent.run_reverted': 'Undid everything an agent run changed',
    'agent.revision_promoted': 'Put a version of an agent live',
    'agent.revision_rolled_back': 'Went back to an earlier version of an agent',
    'agent.project_policy_changed': 'Changed what agents may do in a project',
    'agent.workspace_policy_changed': 'Changed what agents may do in the workspace',
    'agent.standing_approval_made': 'Turned on "Always do this" for an agent',
    'agent.standing_approval_ended': 'Ended an "Always do this" approval',
    'agent.egress_refused': 'Blocked an agent from reaching a site',
    'agent.egress_allowlist': 'Changed the sites agents may reach',
    'audit.amended': 'Added to an earlier record',
    'audit.person_redacted': 'Removed a person\'s details from the audit log',
    'instance.audit_redact_person': 'Asked to remove a person\'s details from the audit log',
    'permission.refused': 'Tried something their role does not allow',
    'permission.enforcement_mode': 'Changed how permissions are enforced',
    'ai.instruction_pattern_added': 'Added a pattern for spotting hidden instructions',
    'ai.instruction_pattern_removed': 'Removed a pattern for spotting hidden instructions',
    'knowledge.reindex': 'Started reading the workspace again for AI search',
    'knowledge.reindex_cancel': 'Stopped reading the workspace again for AI search',
    'knowledge.reembed': 'Rebuilt what AI search knows',
    'knowledge.retry_files': 'Retried the files AI search could not read',
    'knowledge.erase_document': 'Removed a document from AI search',
    'knowledge.erase_person': 'Removed a person\'s content from AI search',
    'knowledge.exclusion_remove': 'Let AI search read something again',
    'member.update': 'Changed a member\'s role or details',
    'api_token.renewed': 'Renewed an access token',
    'billing.contract.update': 'Changed a project\'s billing contract',
    'billing.milestone.create': 'Added a billing milestone',
    'billing.milestone.update': 'Changed a billing milestone',
    'billing.invoice.draft': 'Drafted an invoice',
    'billing.invoice.update': 'Changed an invoice',
    'billing.invoice.sent': 'Marked an invoice as sent',
    'billing.invoice.paid': 'Marked an invoice as paid',
    'billing.invoice.delete': 'Deleted an invoice',
    'goal.create': 'Created a goal',
    'goal.update': 'Changed a goal',
    'goal.archive': 'Archived a goal',
    'goal.restore': 'Restored a goal',
    'oauth.grant_created': 'Connected an outside app',
    'oauth.grant_revoked': 'Disconnected an outside app',
    'oauth.grant_narrowed': 'Reduced what an outside app may do',
    'oauth.client_approval_requested': 'Asked for an outside app to be approved',
    'oauth.client_approved': 'Approved an outside app',
    'oauth.client_approval_denied': 'Turned down an outside app',
    'oauth.client_approval_revoked': 'Withdrew the approval of an outside app',
    'oauth.client_registered': 'Registered an outside app',
    'oauth.client_revoked': 'Removed an outside app',
    'connector.connect': 'Connected a service',
    'connector.revoke': 'Disconnected a service',
    'connector.broken': 'A connected service stopped working',
    'connector.channels_set': 'Chose the Slack channels agents may use',
    'connector.call': 'An agent read from a connected service',
    'agent_session.delegated': 'Handed a task to an outside agent',
    'agent_session.endpoint_saved': 'Saved where an outside agent is reached',
    'agent_session.completed': 'An outside agent finished its work',
    'agent_session.failed': 'An outside agent\'s work failed',
    'agent_session.revoked': 'An outside agent\'s access was withdrawn',
    'agent_session.unresponsive': 'An outside agent stopped answering',
    'sso.config_update': 'Changed the single sign-on settings',
    'sso.domain_verified': 'Verified a sign-in domain',
    'sso.domain_unverified': 'A sign-in domain is no longer verified',
    'sso.login_refused': 'Refused a single sign-on login',
    'scim.config_update': 'Changed the member sync settings',
    'scim.token_rotate': 'Replaced the member sync access token',
    'scim.user_invite': 'Member sync invited a person',
    'scim.user_provision': 'Member sync added a person',
    'scim.user_activate': 'Member sync turned a person back on',
    'scim.user_deactivate': 'Member sync turned a person off',
    'pto.create': 'Asked for time off',
    'pto.approved': 'Approved time off',
    'pto.rejected': 'Turned down time off',
    'pto.pending': 'Set time off back to waiting',
    'secret.create': 'Saved a secret',
    'secret.rotate': 'Replaced a secret',
    'secret.revoke': 'Removed a secret',
    'secret.orphan': 'A secret is no longer used by anything',
    'secret.resolve_failed': 'A secret could not be read',
    'secret.reencrypt': 'Encrypted the saved secrets again',
    'automation.task.update': 'An automation changed a task',
    'automation.task.comment': 'An automation added a comment',
    'automation.task.create': 'An automation created a task',
    'automation.task.create_subtask': 'An automation added a subtask',
    'automation.task.assign': 'An automation changed who a task is assigned to',
    'automation.task.notify': 'An automation sent a notification',
    'automation.task.set_status': 'An automation changed the status',
    'automation.task.set_priority': 'An automation changed the priority',
    'workflow.add_comment': 'A workflow added a comment',
    'workflow.assign': 'A workflow changed who a task is assigned to',
    'workflow.create_subtask': 'A workflow added a subtask',
    'workflow.notify': 'A workflow sent a notification',
    'workflow.run_agent': 'A workflow ran an agent',
    'workflow.set_priority': 'A workflow changed the priority',
    'workflow.set_status': 'A workflow changed the status',
});

/* `meta.action` of an agent's row, for what the agent registry (Modules/Agents/registry.js) does not hold:
 * what only a person may do, and the steps the server takes for an agent. */
const ACTIONS = Object.freeze({
    'model.call': 'Ask the AI model',
    'run.start': 'Start an agent run',
    'run.revert': 'Undo everything a run changed',
    'undo': 'Undo a change',
    'session.taken_up': 'Take up work handed to an outside agent',
    'session.activity': 'Report progress on handed-over work',
    'session.complete': 'Finish handed-over work',
    'session.fail': 'Give up handed-over work',
    'workflow.agent_run': 'Workflow step: run an agent',
    'workflow.tool_call': 'Workflow step: make a change',
    'workflow.human_approval': 'Workflow step: ask a person to approve',
    'workflow.fan_out': 'Workflow step: split into side-by-side steps',
    'workflow.fan_in': 'Workflow step: wait for the side-by-side steps',
    'workflow.condition': 'Workflow step: check a condition',
    'workflow.wait': 'Workflow step: wait',
    'workflow.timer': 'Workflow step: wait until a set time',
    'workflow.loop': 'Workflow step: repeat',
    'workflow.external_agent': 'Workflow step: hand over to an outside agent',
    'workflow.automation_rule': 'Workflow step: run an automation',
    'workflow.loop.run_limit': 'Run an agent again in a repeating workflow',
    'workflow.approval.decide': 'Decide a workflow approval',
    'workflow.approval.reassign': 'Pass a workflow approval to someone else',
    'workflow.definition.create': 'Create a workflow',
    'workflow.definition.update': 'Edit a workflow',
    'workflow.definition.enable': 'Turn a workflow on or off',
    'workflow.definition.delete': 'Delete a workflow',
    'workflow.step.retry': 'Retry a workflow step',
    'workflow.step.skip': 'Skip a workflow step',
    'workflow.step.resume': 'Resume a workflow step',
    'workflow.step.compensate': 'Undo a workflow step',
    'task.delete': 'Delete a task',
    'tasks.unknown': 'Change a task in a way that has no name',
    'tasks.import': 'Import tasks',
    'tasks.cascade': 'Change a task and the tasks under it',
    'task.relation.unknown': 'Change a task\'s links in a way that has no name',
    'project.delete': 'Delete or close a project',
    'project.status.set': 'Change a project\'s status',
    'project.agent_policy.edit': 'Change what agents may do in a project',
    'project.agent_limits.edit': 'Change the limits for agents in a project',
    'project.agent_manager.edit': 'Change a project\'s project manager settings',
    'project.standing_approval.end': 'End an "Always do this" approval',
    'workspace.agent_policy.edit': 'Change what agents may do in the workspace',
    'member.remove': 'Change who is a member',
    'member.seat': 'Change who may use the time tracker',
    'member.invite': 'Invite a member',
    'permissions.edit': 'Change roles and permissions',
    'billing.*': 'Change anything to do with billing',
    'deploy.production': 'Deploy to the live site',
    'token.manage': 'Manage access tokens',
    'goal.create': 'Create a goal',
    'goal.update': 'Edit a goal',
    'goal.archive': 'Archive a goal',
    'goal.restore': 'Restore a goal',
    'goal.write': 'Change a goal',
    'goal.target.add': 'Add a target to a goal',
    'goal.target.edit': 'Edit a goal\'s target',
    'goal.target.remove': 'Remove a goal\'s target',
    'proposal.approve': 'Approve a proposal',
    'proposal.decline': 'Decline a proposal',
    'proposal.undo': 'Undo an approved proposal',
    'queue.hand_over': 'Hand work over to an agent',
    'queue.take_back': 'Take work back from an agent',
    'agent.create': 'Create an agent',
    'agent.update': 'Edit an agent',
    'agent.delete': 'Delete an agent',
    'agent.pause': 'Pause an agent',
    'agent.resume': 'Resume an agent',
    'agent.pause_all': 'Pause all agents',
    'agent.settings.edit': 'Change the AI settings',
    'agent.routing_policy.edit': 'Change how work is shared out to agents',
    'agent.skill.create': 'Create a skill',
    'agent.skill.update': 'Edit a skill',
    'agent.skill.retire': 'Retire a skill',
    'agent.memory.add': 'Add to what agents remember',
    'agent.memory.update': 'Edit what agents remember',
    'agent.preferences.edit': 'Change a person\'s AI preferences',
    'agent.run.stop': 'Stop an agent run',
    'agent.run.revert': 'Undo everything a run changed',
    'agent.account.link': 'Link an AI account',
    'agent.account.unlink': 'Unlink an AI account',
    'agent.schedule.create': 'Add a schedule for an agent',
    'agent.schedule.update': 'Edit an agent\'s schedule',
    'agent.schedule.delete': 'Delete an agent\'s schedule',
    'agent.revision.create': 'Save a new version of an agent',
    'agent.revision.promote': 'Put a version of an agent live',
    'agent.revision.rollback': 'Go back to an earlier version of an agent',
    'agent.change.undo': 'Undo an agent\'s change',
    'automation.draft': 'Draft an automation with AI',
    'automation.update': 'Edit an automation',
    'automation.enable': 'Turn an automation on or off',
    'automation.delete': 'Delete an automation',
    'automation.apply': 'Run an automation on the tasks already there',
    'assignment.suggestion.accept': 'Accept a suggested assignee',
    'assignment.suggestion.dismiss': 'Dismiss a suggested assignee',
    'assignment.suggestion.undo': 'Undo a suggested assignee',
    'timesheet.review': 'Review a timesheet',
    'pto.decide': 'Approve or turn down time off',
    'integration.connect': 'Connect an integration',
    'integration.update': 'Change an integration',
    'page.comment': 'Comment on a doc',
    'page.share': 'Share a doc',
    'page.ai': 'Write in a doc with AI',
    'page.version.save': 'Save a version of a doc',
    'page.version.restore': 'Restore a version of a doc',
    'page.version.rename': 'Rename a version of a doc',
    'page.review': 'Mark a doc as reviewed',
    'page.approve': 'Approve a doc',
    'page.restore': 'Restore a doc',
    'page.image': 'Add an image to a doc',
    'share.public': 'Share with a public link',
    'intake.review': 'Review what a form sent in',
    'sprint.scrum': 'Make a list a sprint',
    'sprint.start': 'Start a sprint',
    'sprint.complete': 'Complete a sprint',
    'sprint.create': 'Create a list',
    'sprint.update': 'Edit a list',
    'folder.update': 'Edit a folder',
    'trash.restore': 'Restore from the trash',
    'sample_data.remove': 'Remove the sample data',
    'account.security': 'Change sign-in or password settings',
    'agent.run.start': 'Start an agent on a task',
    'agent.session.delegate': 'Hand a task to an outside agent',
    'agent.session.endpoint': 'Set where an outside agent is reached',
    'ai.answer.post': 'Post an AI answer in a conversation',
    'ai.memory.edit': 'Change what the AI remembers about a person',
    'ai.spend': 'Ask the workspace AI for an answer',
    'billing.entries': 'Mark time as billable or not',
    'billing.project': 'Change a project\'s billing details',
    'billing.rates': 'Change billing rates',
    'calendar.feed': 'Make or change a calendar feed',
    'chat.channel': 'Read or write in a channel',
    'chat.direct': 'Read or write a direct message',
    'dashboard.manage': 'Make or change a dashboard',
    'email.send': 'Send an email',
    'email_in.manage': 'Change how email comes in as tasks',
    'export.workspace': 'Export the workspace',
    'file.delete': 'Delete a file',
    'form.manage': 'Make or change a form',
    'notification.send': 'Send a notification',
    'portfolio.edit': 'Change a portfolio',
    'project.settings': 'Change a project\'s settings',
    'project.tags.edit': 'Change a project\'s tags',
    'pto.request': 'Ask for time off',
    'recurring.manage': 'Set a task to repeat',
    'reminder.manage': 'Make or change a reminder',
    'report.schedule': 'Schedule a report',
    'task_types.edit': 'Change the task types',
    'template.apply': 'Use a task template',
    'template.import': 'Import settings from a template',
    'template.save': 'Save a project as a template',
    'template.update': 'Change a saved project template',
    'timelog.delete': 'Delete logged time',
    'timesheet.submit': 'Send a timesheet for approval',
    'unread.reset': 'Clear unread counts',
    'webhook.manage': 'Make or change a webhook',
    'workload.move': 'Move planned work',
    'workspace.create': 'Make a workspace',
    'workspace.settings': 'Change the workspace\'s settings',
});

const AGENT_ROWS = Object.freeze(['agent.action', 'agent.action_refused', 'agent.action_undone']);

const actionLabel = (key) => {
    const known = require('../Agents/registry').get(key);
    return (known && known.label) || ACTIONS[key] || '';
};

/* The words for one row: what the agent did or tried on an agent's row, what happened on any other. */
const labelOf = (row) => {
    const tried = String((row && row.meta && row.meta.action) || '');
    const happened = EVENTS[String((row && row.action) || '')] || '';
    if (!tried) return happened;
    return AGENT_ROWS.includes(row.action) ? actionLabel(tried) || happened : happened;
};

module.exports = { EVENTS, ACTIONS, AGENT_ROWS, labelOf };
