#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const META_FILE = path.join(__dirname, 'env-doc.meta.json');
const BACKEND_ROOTS = ['Config', 'Modules', 'utils', 'common-storage', 'middlewares', 'event', 'socket', 'index.js', 'server.js', 'cron.js', 'scripts'];
const FRONTEND_ROOTS = ['frontend/src', 'frontend/vue.config.js', 'frontend/public'];
const OUTPUTS = {
    docs: path.join(ROOT, 'docs', 'ENV.md'),
    envExample: path.join(ROOT, '.env.example'),
    frontendExample: path.join(ROOT, 'frontend', '.env.example')
};
const BLOCK_START = '# ── generated by scripts/env-doc.js — do not edit below; run `node scripts/env-doc.js` ──';
const BLOCK_END = '# ── end generated ──';
const GROUP_ORDER = ['server', 'database', 'auth', 'mail', 'storage', 'ai', 'calling', 'integrations', 'billing', 'security', 'logging', 'limits', 'jobs', 'frontend', 'general'];

function walk(target, out = []) {
    if (!fs.existsSync(target)) return out;
    if (fs.statSync(target).isFile()) {
        if (/\.(js|mjs|cjs|vue)$/.test(target)) out.push(target);
        return out;
    }
    for (const entry of fs.readdirSync(target)) {
        if (entry === 'node_modules' || entry === 'dist') continue;
        walk(path.join(target, entry), out);
    }
    return out;
}

const SELF = path.join(ROOT, 'scripts', 'env-doc.js');

const literal = (raw) => {
    const value = raw.trim();
    const m = value.match(/^(['"`])(.*)\1$/);
    if (m) return m[2];
    if (/^-?\d+(\.\d+)?$/.test(value) || value === 'true' || value === 'false') return value;
    return undefined;
};

// `process.env.X`, `process.env['X']` and `env.X` where `env` is process.env by
// alias or default parameter. A trailing `|| <literal>` is recorded as the default.
function scanBackend() {
    const keys = {};
    const note = (key, file, def) => {
        const entry = keys[key] || (keys[key] = { files: new Set(), default: undefined });
        entry.files.add(path.relative(ROOT, file));
        if (entry.default === undefined && def !== undefined) entry.default = def;
    };
    for (const root of BACKEND_ROOTS) {
        for (const file of walk(path.join(ROOT, root))) {
            if (file === SELF) continue;
            const text = fs.readFileSync(file, 'utf8');
            for (const m of text.matchAll(/process\.env\.([A-Z][A-Z0-9_]*)(?:\s*\|\|\s*([^;,)\n]+))?/g)) note(m[1], file, literal(m[2] || ''));
            for (const m of text.matchAll(/process\.env\[['"]([A-Z][A-Z0-9_]*)['"]\]/g)) note(m[1], file);
            if (/\benv\s*=\s*process\.env\b/.test(text)) {
                for (const m of text.matchAll(/\benv\.([A-Z][A-Z0-9_]*)(?:\s*\|\|\s*([^;,)\n]+))?/g)) note(m[1], file, literal(m[2] || ''));
            }
        }
    }
    return keys;
}

function scanFrontend() {
    const keys = {};
    for (const root of FRONTEND_ROOTS) {
        for (const file of walk(path.join(ROOT, root))) {
            const text = fs.readFileSync(file, 'utf8');
            for (const m of text.matchAll(/VUE_APP_[A-Z0-9_]+/g)) {
                (keys[m[0]] || (keys[m[0]] = { files: new Set() })).files.add(path.relative(ROOT, file));
            }
        }
    }
    return keys;
}

function loadMeta() {
    return JSON.parse(fs.readFileSync(META_FILE, 'utf8'));
}

function handWrittenKeys(text) {
    const head = text.split(BLOCK_START)[0];
    const keys = new Set();
    for (const line of head.split('\n')) {
        const m = line.match(/^#?\s*([A-Z][A-Z0-9_]*)=/);
        if (m) keys.add(m[1]);
    }
    return keys;
}

const quote = (value) => (value === undefined || value === '' ? '""' : /^[A-Za-z0-9_./:-]+$/.test(value) ? value : `"${value}"`);

function renderEnvBlock(meta, keys, handWritten) {
    const rows = keys.filter((k) => !handWritten.has(k)).sort();
    const lines = [BLOCK_START, '# Every variable the backend reads that is not set above. Defaults apply when unset.'];
    let group = null;
    for (const key of rows) {
        const m = meta[key];
        if (m.group !== group) {
            group = m.group;
            lines.push('', `# ${group.toUpperCase()}`);
        }
        const suffix = m.secret ? '  # secret' : '';
        lines.push(`# ${m.description}`);
        lines.push(`${m.required ? '' : '# '}${key}=${quote(m.default)}${suffix}`);
    }
    lines.push(BLOCK_END);
    return lines.join('\n');
}

function renderFrontendExample(meta, keys) {
    const lines = ['# Frontend build-time variables (inlined by Vue CLI). Generated by scripts/env-doc.js.', '# Copy to frontend/.env and fill in; the CI build uses placeholders.', ''];
    for (const key of [...keys].sort()) {
        const m = meta[key];
        lines.push(`# ${m.description}${m.secret ? ' (secret)' : ''}`);
        lines.push(`${m.required ? '' : '# '}${key}=${quote(m.default)}`);
    }
    return lines.join('\n') + '\n';
}

function renderDocs(meta, backend, frontend) {
    const all = { ...backend, ...frontend };
    const groups = {};
    for (const key of Object.keys(all)) (groups[meta[key].group] || (groups[meta[key].group] = [])).push(key);
    const lines = ['# Environment variables', '', 'Generated by `node scripts/env-doc.js` from the variables the code reads; `node scripts/env-doc.js --check` fails when this file, `.env.example` or `frontend/.env.example` drifts. Descriptions live in `scripts/env-doc.meta.json`.', '', `Backend variables: ${Object.keys(backend).length}. Frontend build-time variables: ${Object.keys(frontend).length}.`, ''];
    for (const group of GROUP_ORDER.filter((g) => groups[g])) {
        lines.push(`## ${group[0].toUpperCase()}${group.slice(1)}`, '', '| Variable | Required | Default | Description | Read by |', '|---|---|---|---|---|');
        for (const key of groups[group].sort()) {
            const m = meta[key];
            const files = [...all[key].files].sort();
            const readBy = files.length > 2 ? `${files.slice(0, 2).map((f) => `\`${f}\``).join(', ')} +${files.length - 2}` : files.map((f) => `\`${f}\``).join(', ');
            lines.push(`| \`${key}\`${m.secret ? ' (secret)' : ''} | ${m.required ? 'yes' : ''} | ${m.default === undefined || m.default === '' ? '' : `\`${m.default}\``} | ${m.description.replace(/\|/g, '\\|')} | ${readBy} |`);
        }
        lines.push('');
    }
    return lines.join('\n');
}

function build() {
    const meta = loadMeta();
    const backend = scanBackend();
    const frontend = scanFrontend();
    for (const [key, entry] of Object.entries({ ...backend, ...frontend })) {
        if (meta[key] && meta[key].default === undefined && entry.default !== undefined) meta[key] = { ...meta[key], default: entry.default };
    }
    const problems = [];
    const used = new Set([...Object.keys(backend), ...Object.keys(frontend)]);
    for (const key of used) if (!meta[key]) problems.push(`used but not described in scripts/env-doc.meta.json: ${key}`);
    for (const key of Object.keys(meta)) if (!used.has(key) && !meta[key].external) problems.push(`described but never read: ${key}`);
    if (problems.length) return { problems };

    const envExampleText = fs.readFileSync(OUTPUTS.envExample, 'utf8');
    const head = envExampleText.split(BLOCK_START)[0].replace(/\s+$/, '') + '\n\n';
    const files = {
        [OUTPUTS.docs]: renderDocs(meta, backend, frontend),
        [OUTPUTS.envExample]: head + renderEnvBlock(meta, Object.keys(backend), handWrittenKeys(envExampleText)) + '\n',
        [OUTPUTS.frontendExample]: renderFrontendExample(meta, Object.keys(frontend))
    };
    return { problems, files };
}

function check() {
    const { problems, files } = build();
    if (problems.length) return problems;
    return Object.entries(files)
        .filter(([file, content]) => !fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== content)
        .map(([file]) => `out of date: ${path.relative(ROOT, file)} (run node scripts/env-doc.js)`);
}

function main(argv) {
    if (argv.includes('--check')) {
        const problems = check();
        problems.forEach((p) => process.stderr.write(p + '\n'));
        process.stderr.write(problems.length ? `${problems.length} problem(s)\n` : 'env docs are in sync\n');
        return problems.length ? 1 : 0;
    }
    const { problems, files } = build();
    if (problems.length) {
        problems.forEach((p) => process.stderr.write(p + '\n'));
        return 1;
    }
    for (const [file, content] of Object.entries(files)) {
        fs.mkdirSync(path.dirname(file), { recursive: true });
        fs.writeFileSync(file, content);
        process.stdout.write(`wrote ${path.relative(ROOT, file)}\n`);
    }
    return 0;
}

if (require.main === module) process.exitCode = main(process.argv.slice(2));

module.exports = { scanBackend, scanFrontend, build, check };
