#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const META_FILE = path.join(__dirname, 'env-doc.meta.json');
const META_NAME = 'scripts/env-doc.meta.json';
const BACKEND_ROOTS = ['Config', 'Modules', 'utils', 'common-storage', 'middlewares', 'event', 'socket', 'index.js', 'server.js', 'cron.js', 'scripts'];
const FRONTEND_ROOTS = ['frontend/src', 'frontend/vue.config.js', 'frontend/public'];
const OUTPUTS = {
    docs: path.join(ROOT, 'docs', 'ENV.md'),
    envExample: path.join(ROOT, '.env.example'),
    frontendExample: path.join(ROOT, 'frontend', '.env.example')
};
const BLOCK_START = '# ── generated by scripts/env-doc.js — do not edit below; run `node scripts/env-doc.js` ──';
const BLOCK_END = '# ── end generated ──';
const GROUP_ORDER = ['server', 'database', 'auth', 'mail', 'storage', 'ai', 'calling', 'integrations', 'billing', 'security', 'logging', 'limits', 'jobs', 'frontend', 'general'];
const REGENERATE = 'node scripts/env-doc.js';
const STRICT_CHECK = 'npm run env:doc:check';
const SELF = 'scripts/env-doc.js';
const FLAGS = ['secret', 'required', 'external'];
const ENTRY_FIELDS = ['group', 'description', 'default', ...FLAGS];
const UNDESCRIBED = Object.freeze({ group: 'general', description: 'Not described yet.' });

function walk(target, out = []) {
    if (!fs.existsSync(target)) return out;
    if (fs.statSync(target).isFile()) {
        if (/\.(js|mjs|cjs|vue)$/.test(target)) out.push(target);
        return out;
    }
    for (const entry of fs.readdirSync(target)) {
        if (entry === 'node_modules' || entry === 'dist') continue;
        walk(path.join(target, entry), out);
    }
    return out;
}

const sourcesUnder = (roots) => roots.flatMap((root) => walk(path.join(ROOT, root)))
    .map((file) => ({ path: path.relative(ROOT, file).split(path.sep).join('/'), text: fs.readFileSync(file, 'utf8') }))
    .filter((file) => file.path !== SELF);

/* A directory is listed in whatever order the file system gives, which differs between machines. Reading the files
 * in the order of their paths makes the readers and the default the same everywhere. */
const inPathOrder = (files) => [...files].sort((a, b) => (a.path < b.path ? -1 : (a.path > b.path ? 1 : 0)));

const literal = (raw) => {
    const value = raw.trim();
    const m = value.match(/^(['"`])(.*)\1$/);
    if (m) return m[2];
    if (/^-?\d+(\.\d+)?$/.test(value) || value === 'true' || value === 'false') return value;
    return undefined;
};

// `process.env.X`, `process.env['X']` and `env.X` where `env` is process.env by
// alias or default parameter. A trailing `|| <literal>` is recorded as the default:
// the one in the alphabetically first file that names one.
function backendReads(files) {
    const keys = {};
    const note = (key, file, def) => {
        const entry = keys[key] || (keys[key] = { files: [], default: undefined });
        if (!entry.files.includes(file)) entry.files.push(file);
        if (entry.default === undefined && def !== undefined) entry.default = def;
    };
    for (const { path: file, text } of inPathOrder(files)) {
        for (const m of text.matchAll(/process\.env\.([A-Z][A-Z0-9_]*)(?:\s*\|\|\s*([^;,)\n]+))?/g)) note(m[1], file, literal(m[2] || ''));
        for (const m of text.matchAll(/process\.env\[['"]([A-Z][A-Z0-9_]*)['"]\]/g)) note(m[1], file);
        if (/\benv\s*=\s*process\.env\b/.test(text)) {
            for (const m of text.matchAll(/\benv\.([A-Z][A-Z0-9_]*)(?:\s*\|\|\s*([^;,)\n]+))?/g)) note(m[1], file, literal(m[2] || ''));
        }
    }
    return keys;
}

function frontendReads(files) {
    const keys = {};
    for (const { path: file, text } of inPathOrder(files)) {
        for (const m of text.matchAll(/VUE_APP_[A-Z0-9_]+/g)) {
            const entry = keys[m[0]] || (keys[m[0]] = { files: [] });
            if (!entry.files.includes(file)) entry.files.push(file);
        }
    }
    return keys;
}

const scanBackend = () => backendReads(sourcesUnder(BACKEND_ROOTS));
const scanFrontend = () => frontendReads(sourcesUnder(FRONTEND_ROOTS));

function loadMeta() {
    return JSON.parse(fs.readFileSync(META_FILE, 'utf8'));
}

const isPlainObject = (value) => value !== null && typeof value === 'object' && !Array.isArray(value);

function entryProblems(key, entry) {
    if (!isPlainObject(entry)) return [`entry is not an object: ${key}`];
    if (!GROUP_ORDER.includes(entry.group)) return [`unknown group "${entry.group}": ${key}`];
    if (typeof entry.description !== 'string' || !entry.description.trim()) return [`no description: ${key}`];
    if (entry.default !== undefined && typeof entry.default !== 'string') return [`"default" must be text: ${key}`];
    const notFlag = FLAGS.find((flag) => entry[flag] !== undefined && typeof entry[flag] !== 'boolean');
    if (notFlag) return [`"${notFlag}" must be true or false: ${key}`];
    const unknown = Object.keys(entry).find((field) => !ENTRY_FIELDS.includes(field));
    if (unknown) return [`unknown field "${unknown}": ${key}`];
    return [];
}

/* What is wrong with the descriptions file by itself. Nothing here depends on what the code reads, so another change merging first cannot make it fail. */
function metaShapeProblems(meta) {
    if (!isPlainObject(meta)) return [`${META_NAME} must be an object of variables`];
    return Object.keys(meta).sort().flatMap((key) => entryProblems(key, meta[key]));
}

function handWrittenKeys(text) {
    const head = text.split(BLOCK_START)[0];
    const keys = new Set();
    for (const line of head.split('\n')) {
        const m = line.match(/^#?\s*([A-Z][A-Z0-9_]*)=/);
        if (m) keys.add(m[1]);
    }
    return keys;
}

const quote = (value) => (value === undefined || value === '' ? '""' : /^[A-Za-z0-9_./:-]+$/.test(value) ? value : `"${value}"`);

function renderEnvBlock(described, keys, handWritten) {
    const rows = keys.filter((k) => !handWritten.has(k)).sort();
    const lines = [BLOCK_START, '# Every variable the backend reads that is not set above. Defaults apply when unset.'];
    let group = null;
    for (const key of rows) {
        const m = described[key];
        if (m.group !== group) {
            group = m.group;
            lines.push('', `# ${group.toUpperCase()}`);
        }
        const suffix = m.secret ? '  # secret' : '';
        lines.push(`# ${m.description}`);
        lines.push(`${m.required ? '' : '# '}${key}=${quote(m.default)}${suffix}`);
    }
    lines.push(BLOCK_END);
    return lines.join('\n');
}

function renderFrontendExample(described, keys) {
    const lines = ['# Frontend build-time variables (inlined by Vue CLI). Generated by scripts/env-doc.js.', '# Copy to frontend/.env and fill in; the CI build uses placeholders.', ''];
    for (const key of [...keys].sort()) {
        const m = described[key];
        lines.push(`# ${m.description}${m.secret ? ' (secret)' : ''}`);
        lines.push(`${m.required ? '' : '# '}${key}=${quote(m.default)}`);
    }
    return lines.join('\n') + '\n';
}

/* No count of the further readers: with one, a second pull request that adds a reader of the same variable would have to rewrite the row. */
const readByText = (files) => {
    const named = files.slice(0, 2).map((f) => `\`${f}\``).join(', ');
    return files.length > 2 ? `${named} and others` : named;
};

function renderDocs(described, reads) {
    const groups = {};
    for (const key of Object.keys(reads)) (groups[described[key].group] || (groups[described[key].group] = [])).push(key);
    const lines = ['# Environment variables', '', `Generated by \`${REGENERATE}\` from the variables the code reads. Do not edit this file by hand. It is regenerated in the docs pull request that follows merges to \`beta\`, so in between it can be a variable behind the code: \`${STRICT_CHECK}\` says whether this file, \`.env.example\` and \`frontend/.env.example\` are current. Descriptions live in \`${META_NAME}\`.`, ''];
    for (const group of GROUP_ORDER.filter((g) => groups[g])) {
        lines.push(`## ${group[0].toUpperCase()}${group.slice(1)}`, '', '| Variable | Required | Default | Description | Read by |', '|---|---|---|---|---|');
        for (const key of groups[group].sort()) {
            const m = described[key];
            lines.push(`| \`${key}\`${m.secret ? ' (secret)' : ''} | ${m.required ? 'yes' : ''} | ${m.default === undefined || m.default === '' ? '' : `\`${m.default}\``} | ${m.description.replace(/\|/g, '\\|')} | ${readByText(reads[key].files)} |`);
        }
        lines.push('');
    }
    return lines.join('\n');
}

/* A variable the code reads with no description is still printed, by rule, so the generator runs on any tree. */
const describedReads = (meta, reads) => Object.fromEntries(Object.entries(reads).map(([key, read]) => {
    const entry = meta[key] || UNDESCRIBED;
    return [key, entry.default === undefined && read.default !== undefined ? { ...entry, default: read.default } : entry];
}));

function build() {
    const meta = loadMeta();
    const problems = metaShapeProblems(meta);
    if (problems.length) return { problems };

    const backend = scanBackend();
    const frontend = scanFrontend();
    const reads = { ...backend, ...frontend };
    const described = describedReads(meta, reads);
    const envExampleText = fs.readFileSync(OUTPUTS.envExample, 'utf8');
    const head = envExampleText.split(BLOCK_START)[0].replace(/\s+$/, '') + '\n\n';
    return {
        problems,
        drift: {
            undescribed: Object.keys(reads).filter((key) => !meta[key]).sort(),
            unread: Object.keys(meta).filter((key) => !reads[key] && !meta[key].external).sort(),
        },
        files: {
            [OUTPUTS.docs]: renderDocs(described, reads),
            [OUTPUTS.envExample]: head + renderEnvBlock(described, Object.keys(backend), handWrittenKeys(envExampleText)) + '\n',
            [OUTPUTS.frontendExample]: renderFrontendExample(described, Object.keys(frontend))
        }
    };
}

const staleFiles = (files) => Object.entries(files)
    .filter(([file, content]) => !fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== content)
    .map(([file]) => `out of date: ${path.relative(ROOT, file)} (run ${REGENERATE})`);

/* A pull request must describe the variables it reads, which it can do alone. Whether the generated files are current,
 * and whether a description is still read, depends on what else has merged, so those only fail when asked to. */
function driftReport({ undescribed, unread, stale }, strict = false) {
    const own = undescribed.map((key) => `used but not described in ${META_NAME}: ${key}`);
    const drift = [...stale, ...unread.map((key) => `described but never read: ${key}`)];
    return strict ? { problems: [...own, ...drift], warnings: [] } : { problems: own, warnings: drift };
}

function check(built = build(), { strict = false } = {}) {
    if (built.problems.length) return { problems: built.problems, warnings: [] };
    return driftReport({ ...built.drift, stale: staleFiles(built.files) }, strict);
}

function main(argv) {
    const strict = argv.includes('--strict');
    const built = build();
    if (!built.problems.length && !argv.includes('--check')) {
        for (const [file, content] of Object.entries(built.files)) {
            fs.mkdirSync(path.dirname(file), { recursive: true });
            fs.writeFileSync(file, content);
            process.stdout.write(`wrote ${path.relative(ROOT, file)}\n`);
        }
    }
    const { problems, warnings } = check(built, { strict });
    warnings.forEach((warning) => process.stderr.write(`warning: ${warning}\n`));
    problems.forEach((problem) => process.stderr.write(`${problem}\n`));
    if (problems.length) process.stderr.write(`${problems.length} problem(s)\n`);
    else process.stderr.write(warnings.length ? `${warnings.length} warning(s); ${STRICT_CHECK} fails on them\n` : 'env docs are in sync\n');
    return problems.length ? 1 : 0;
}

if (require.main === module) process.exitCode = main(process.argv.slice(2));

module.exports = { backendReads, frontendReads, readByText, metaShapeProblems, driftReport, scanBackend, scanFrontend, loadMeta, build, check };
