const { test, expect, asRole } = require('../support/test');
const { uniqueSuffix } = require('../support/fixtures');

// firebase-messaging-sw.js is generated by frontend/config.sh and gitignored, so a
// plain build serves a 404 for it and Chromium logs the failed worker fetch as a
// console error that says nothing about the screen under test.
const MISSING_SERVICE_WORKER = /bad HTTP response code \(404\) was received when fetching the script/;

function trackConsoleErrors(page) {
    const errors = [];
    page.on('console', (msg) => {
        if (msg.type() === 'error' && !MISSING_SERVICE_WORKER.test(msg.text())) errors.push(msg.text());
    });
    page.on('pageerror', (err) => errors.push(String(err)));
    return errors;
}

test.describe('reports screens as the owner', () => {
    test.use(asRole('owner'));
    // The custom report builder hides itself below 768px (mobile), so give the
    // desktop layout room.
    test.use({ viewport: { width: 1440, height: 900 } });

    test('the custom report builder renders with the live preview', async ({ page, state }) => {
        const errors = trackConsoleErrors(page);
        await page.goto(`/#/${state.companyId}/custom-reports`);
        await expect(page.getByText('New report', { exact: true })).toBeVisible();
        await expect(page.getByRole('button', { name: 'Save', exact: true })).toBeVisible();
        expect(errors).toEqual([]);
    });

    test('the dashboards hub lists dashboards', async ({ page, state }) => {
        const errors = trackConsoleErrors(page);
        await page.goto(`/#/${state.companyId}/dashboards`);
        await expect(page.getByRole('button', { name: /Dashboard/ }).first()).toBeVisible();
        expect(errors).toEqual([]);
    });

    test('the integrations hub renders its tiles', async ({ page, state }) => {
        const errors = trackConsoleErrors(page);
        await page.goto(`/#/${state.companyId}/integrations`);
        await expect(page.getByText('Marketplace', { exact: true })).toBeVisible();
        expect(errors).toEqual([]);
    });

    test('the connections page renders', async ({ page, state }) => {
        const errors = trackConsoleErrors(page);
        await page.goto(`/#/${state.companyId}/connections`);
        await expect(page.getByText('Connect', { exact: true }).first()).toBeVisible();
        expect(errors).toEqual([]);
    });

    test('the external data page renders the catalog', async ({ page, state }) => {
        const errors = trackConsoleErrors(page);
        await page.goto(`/#/${state.companyId}/external-data`);
        await expect(page.getByText('Microsoft Teams', { exact: true })).toBeVisible();
        expect(errors).toEqual([]);
    });

    test('the settings integrations page renders the webhook panel', async ({ page, state }) => {
        const errors = trackConsoleErrors(page);
        await page.goto(`/#/${state.companyId}/settings/integrations`);
        await expect(page.getByText('Integrations', { exact: true }).first()).toBeVisible();
        expect(errors).toEqual([]);
    });

    test('the project velocity report renders', async ({ page, state }) => {
        const errors = trackConsoleErrors(page);
        await page.goto(`/#/${state.companyId}/reports/velocity`);
        await expect(page.getByText('Velocity', { exact: true }).first()).toBeVisible();
        expect(errors).toEqual([]);
    });

    test('the project milestones report renders', async ({ page, state }) => {
        const errors = trackConsoleErrors(page);
        await page.goto(`/#/${state.companyId}/reports/milestones`);
        await expect(page.getByText('Milestones', { exact: true }).first()).toBeVisible();
        expect(errors).toEqual([]);
    });
});

test.describe('reports screens as a member', () => {
    test.use(asRole('member'));
    test.use({ viewport: { width: 1440, height: 900 } });

    test('a member reaches the dashboards hub and the custom report builder', async ({ page, state }) => {
        const errors = trackConsoleErrors(page);
        await page.goto(`/#/${state.companyId}/dashboards`);
        await expect(page.getByRole('button', { name: /Dashboard/ }).first()).toBeVisible();
        await page.goto(`/#/${state.companyId}/custom-reports`);
        await expect(page.getByText('New report', { exact: true })).toBeVisible();
        expect(errors).toEqual([]);
    });
});

test.describe('reports screens as the guest', () => {
    test.use(asRole('guest'));

    test('the guest can open the integrations hub', async ({ page, state }) => {
        const errors = trackConsoleErrors(page);
        await page.goto(`/#/${state.companyId}/integrations`);
        await expect(page.getByText('Marketplace', { exact: true })).toBeVisible();
        expect(errors).toEqual([]);
    });
});

// Regression coverage driven through the API fixtures the e2e layer provides.
test.describe('reports regressions', () => {
    // REP-01 — legacy POST /api/v1/dashboard runs a body-supplied Mongo method,
    // letting any role overwrite another user's dashboard.
    test.fail('REP-01 legacy /dashboard cannot overwrite another user\'s dashboard', async ({ loginAs }) => {
        const owner = await loginAs('owner');
        const guest = await loginAs('guest');
        const priv = await owner.api.post('/api/v1/dashboards', { title: `[e2e] rep01 ${uniqueSuffix()}`, visibility: 'private' });
        const id = priv.body.data._id;

        const write = await guest.api.post('/api/v1/dashboard', { queryObject: [{ _id: id }, { $set: { title: 'pwned' } }], method: 'updateOne' });
        const after = await owner.api.get(`/api/v1/dashboards/${id}`);
        await owner.api.delete(`/api/v1/dashboards/${id}`);

        const refused = write.status >= 400 || (write.body && write.body.status === false);
        expect(refused && after.body.data.title !== 'pwned').toBe(true);
    });

    // REP-04 — webhook URL validation only checks the protocol, so an internal host
    // is accepted (blind SSRF via the dispatcher).
    test.fail('REP-04 a webhook aimed at the cloud metadata address is refused', async ({ loginAs }) => {
        const owner = await loginAs('owner');
        const res = await owner.api.post('/api/v2/webhooks', { name: `[e2e] ssrf ${uniqueSuffix()}`, url: 'http://169.254.169.254/latest/meta-data', events: ['task.created'] });
        if (res.body && res.body.data && res.body.data._id) {
            await owner.api.delete(`/api/v2/webhooks/${res.body.data._id}`);
        }
        expect(res.body.status).toBe(false);
    });
});
